spring:
  data:
    redis:
      host: redis_1
      port: 6379
      password: "${custom.prod.redis.password}"
  datasource:
    url: jdbc:mysql://mysql_1:3306/glog_prod
    username: lldjlocal
    password: "${custom.prod.db.password}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

logging:
  level:
    com.example: TRACE
    org.hibernate.SQL: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  site:
    domain: "${custom.prod.domain}"
    backUrl: "${custom.prod.backUrl}"
    frontUrl: "${custom.prod.frontUrl}"